name: portfolio_website
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.0.0

  flutter_hooks: ^0.16.0-nullsafety.0
  hooks_riverpod: ^0.13.1+1
  google_fonts: ^2.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets :
#    - assets/pomogtd_icon_thumbnail.png
#    - assets/portfolio_thumbnail.png
#    - assets/selfie.jpg
    - images/
    - google_fonts/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: google_fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
        - asset: google_fonts/Noto_Sans_JP/NotoSansJP-Medium.otf
          weight: 600

